### ISSUE TITLE
[Feature Request] 为 key 增加一些新的查询用法

### ISSUE THREAD

**Issue by enpitsuLin** [Otto-J/unstorage-xlog-driver#3]
现在暂时是通过 `<id>.md`来查询指定 id 的 note，如果和 nuxt-content 集成的话，可能我对于 `[slug].vue` 会想要直接通过 route params slug 来查询，会比较麻烦 如果可以通过 `storage.getItem('slug:<string>')` 来快速查询。

通过这个功能可以保持原先默认的行为 `storage.getItem('1.md')` 是获取 id 为 1 的 note ，然后可以添加更多的类似的查询 key 功能，比如：
- `id:<number>`
- `slug:<string>`
- `title:<string>`

**Comment by Otto-J** [comment]
嗯，赞同，这需要保证 slug 唯一，不过问题不大

**Comment by enpitsuLin** [comment]
我看了下 xLog 应该是限制了重复 slug 的文章被创建，去 discord 里面问问 csb 根本上可以不可以创建重复的
